- name: Set up Go
  uses: actions/setup-go@v5
  with:
    go-version: stable
- name: Run go tidy
  run: |
    cd go/ldrs-sf
    go mod tidy
- name: Run go make
  env:
    CARGO_DIST_TARGET: ${{ join(matrix.targets, '-') }}
  run: make build-go-ci
- name: Upload ldrs-sf artifacts
  uses: actions/upload-artifact@v4
  with:
    name: artifacts-ldrs-sf-${{ join(matrix.targets, '_') }}
    path: target/ldrs_sf/
