[workspace]

[[package]]
name = "ldrs"
publish = false
git_release_enable = false
git_tag_name = "v{{ version }}"
changelog_update = true
semver_check = false

[[package]]
name = "ldrs-test-fixtures"
release = false
publish = false

[[package]]
name = "ldrs-arrow"
release = false
publish = false

[[package]]
name = "ldrs-storage"
release = false
publish = false

[[package]]
name = "ldrs-parquet"
release = false
publish = false

[[package]]
name = "ldrs-postgres"
release = false
publish = false

[[package]]
name = "ldrs-delta"
release = false
publish = false
