name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Rust
        uses: actions/setup-go@v5
      - name: Setup Postegres
        run: test_data/setup_test.sh
        shell: bash
      - run: cargo test
      - name: Shutdown Postgres
        run: test_data/shutdown_test.sh
        shell: bash
